services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    networks:
      - bingy-network

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    restart: unless-stopped
    networks:
      - bingy-network
    depends_on:
      - backend

networks:
  bingy-network:
