import { z } from "zod";

const envSchema = z.object({
	PORT: z.string().default("3000"),
	LOG_LEVEL: z.string().default("info"),
	NODE_ENV: z.enum(["development", "production"]).default("development"),
	PEPPER_KEY: z.string(),
	DB_HOST: z.string().default("localhost"),
	DB_USER: z.string(),
	DB_PASSWORD: z.string(),
	DB_NAME: z.string(),
	DB_PORT: z.string().default("5432"),
	REDIS_HOST: z.string().default("localhost"),
	REDIS_PORT: z.string().default("6379"),
	REDIS_PASSWORD: z.string(),
	REDIS_URL: z.string().default("redis:/localhost:6379"),
	GOOGLE_CLIENT_ID: z.string(),
	GOOGLE_CLIENT_SECRET: z.string(),
	BASE_URL: z.string(),
	API_VERSION: z.string(),
	FRONT_URL: z.string(),
	RESEND_API_KEY: z.string(),
	TMDB_API_KEY: z.string(),
	TRANSACTIONAL_EMAIL: z.string(),
	APP_NAME: z.string(),
	BUCKET_URL: z.string(),
	R2_PUBLIC_URL: z.string(),
	R2_BUCKET_NAME: z.string(),
	CLOUDFLARE_ACCOUNT_ID: z.string(),
	S3_ACCESS_KEY_ID: z.string(),
	S3_SECRET_ACCESS_KEY: z.string(),
	API_URL: z.string(),
});

export default envSchema.parse(process.env);
