/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as GoodbyeRouteImport } from './routes/goodbye'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as TvTvIdRouteImport } from './routes/tv/$tvId'
import { Route as PersonPersonIdRouteImport } from './routes/person/$personId'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections/$collectionId'
import { Route as AuthWelcomeRouteImport } from './routes/_auth/welcome'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as UserUsernameIndexRouteImport } from './routes/user/$username/index'
import { Route as UserUsernameWatchlistRouteImport } from './routes/user/$username/watchlist'
import { Route as UserUsernameListsRouteImport } from './routes/user/$username/lists'
import { Route as UserUsernameInProgressRouteImport } from './routes/user/$username/in-progress'
import { Route as UserUsernameHistoryRouteImport } from './routes/user/$username/history'
import { Route as TvTvIdSeasonsRouteImport } from './routes/tv/$tvId_/seasons'
import { Route as TvTvIdEpisodesRouteImport } from './routes/tv/$tvId_/episodes'
import { Route as TvTvIdCreditsRouteImport } from './routes/tv/$tvId_/credits'
import { Route as MoviesMovieIdCreditsRouteImport } from './routes/movies/$movieId_/credits'
import { Route as TvTvIdSeasonSeasonNumberRouteImport } from './routes/tv/$tvId_/season_/$seasonNumber'
import { Route as TvTvIdSeasonSeasonNumberCreditsRouteImport } from './routes/tv/$tvId_/season_/$seasonNumber_/credits'
import { Route as TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRouteImport } from './routes/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber'
import { Route as TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRouteImport } from './routes/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber_/credits'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTvIdRoute = TvTvIdRouteImport.update({
  id: '/tv/$tvId',
  path: '/tv/$tvId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonPersonIdRoute = PersonPersonIdRouteImport.update({
  id: '/person/$personId',
  path: '/person/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const UserUsernameIndexRoute = UserUsernameIndexRouteImport.update({
  id: '/user/$username/',
  path: '/user/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameWatchlistRoute = UserUsernameWatchlistRouteImport.update({
  id: '/user/$username/watchlist',
  path: '/user/$username/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameListsRoute = UserUsernameListsRouteImport.update({
  id: '/user/$username/lists',
  path: '/user/$username/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameInProgressRoute = UserUsernameInProgressRouteImport.update({
  id: '/user/$username/in-progress',
  path: '/user/$username/in-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameHistoryRoute = UserUsernameHistoryRouteImport.update({
  id: '/user/$username/history',
  path: '/user/$username/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTvIdSeasonsRoute = TvTvIdSeasonsRouteImport.update({
  id: '/tv/$tvId_/seasons',
  path: '/tv/$tvId/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTvIdEpisodesRoute = TvTvIdEpisodesRouteImport.update({
  id: '/tv/$tvId_/episodes',
  path: '/tv/$tvId/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTvIdCreditsRoute = TvTvIdCreditsRouteImport.update({
  id: '/tv/$tvId_/credits',
  path: '/tv/$tvId/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdCreditsRoute = MoviesMovieIdCreditsRouteImport.update({
  id: '/movies/$movieId_/credits',
  path: '/movies/$movieId/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const TvTvIdSeasonSeasonNumberRoute =
  TvTvIdSeasonSeasonNumberRouteImport.update({
    id: '/tv/$tvId_/season_/$seasonNumber',
    path: '/tv/$tvId/season/$seasonNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const TvTvIdSeasonSeasonNumberCreditsRoute =
  TvTvIdSeasonSeasonNumberCreditsRouteImport.update({
    id: '/tv/$tvId_/season_/$seasonNumber_/credits',
    path: '/tv/$tvId/season/$seasonNumber/credits',
    getParentRoute: () => rootRouteImport,
  } as any)
const TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute =
  TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRouteImport.update({
    id: '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber',
    path: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute =
  TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRouteImport.update({
    id: '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber_/credits',
    path: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goodbye': typeof GoodbyeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/welcome': typeof AuthWelcomeRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/movies': typeof MoviesIndexRoute
  '/tv': typeof TvIndexRoute
  '/movies/$movieId/credits': typeof MoviesMovieIdCreditsRoute
  '/tv/$tvId/credits': typeof TvTvIdCreditsRoute
  '/tv/$tvId/episodes': typeof TvTvIdEpisodesRoute
  '/tv/$tvId/seasons': typeof TvTvIdSeasonsRoute
  '/user/$username/history': typeof UserUsernameHistoryRoute
  '/user/$username/in-progress': typeof UserUsernameInProgressRoute
  '/user/$username/lists': typeof UserUsernameListsRoute
  '/user/$username/watchlist': typeof UserUsernameWatchlistRoute
  '/user/$username': typeof UserUsernameIndexRoute
  '/tv/$tvId/season/$seasonNumber': typeof TvTvIdSeasonSeasonNumberRoute
  '/tv/$tvId/season/$seasonNumber/credits': typeof TvTvIdSeasonSeasonNumberCreditsRoute
  '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber': typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
  '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits': typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/goodbye': typeof GoodbyeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/settings': typeof AuthSettingsRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/welcome': typeof AuthWelcomeRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/movies': typeof MoviesIndexRoute
  '/tv': typeof TvIndexRoute
  '/movies/$movieId/credits': typeof MoviesMovieIdCreditsRoute
  '/tv/$tvId/credits': typeof TvTvIdCreditsRoute
  '/tv/$tvId/episodes': typeof TvTvIdEpisodesRoute
  '/tv/$tvId/seasons': typeof TvTvIdSeasonsRoute
  '/user/$username/history': typeof UserUsernameHistoryRoute
  '/user/$username/in-progress': typeof UserUsernameInProgressRoute
  '/user/$username/lists': typeof UserUsernameListsRoute
  '/user/$username/watchlist': typeof UserUsernameWatchlistRoute
  '/user/$username': typeof UserUsernameIndexRoute
  '/tv/$tvId/season/$seasonNumber': typeof TvTvIdSeasonSeasonNumberRoute
  '/tv/$tvId/season/$seasonNumber/credits': typeof TvTvIdSeasonSeasonNumberCreditsRoute
  '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber': typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
  '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits': typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/goodbye': typeof GoodbyeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_auth/welcome': typeof AuthWelcomeRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/person/$personId': typeof PersonPersonIdRoute
  '/tv/$tvId': typeof TvTvIdRoute
  '/movies/': typeof MoviesIndexRoute
  '/tv/': typeof TvIndexRoute
  '/movies/$movieId_/credits': typeof MoviesMovieIdCreditsRoute
  '/tv/$tvId_/credits': typeof TvTvIdCreditsRoute
  '/tv/$tvId_/episodes': typeof TvTvIdEpisodesRoute
  '/tv/$tvId_/seasons': typeof TvTvIdSeasonsRoute
  '/user/$username/history': typeof UserUsernameHistoryRoute
  '/user/$username/in-progress': typeof UserUsernameInProgressRoute
  '/user/$username/lists': typeof UserUsernameListsRoute
  '/user/$username/watchlist': typeof UserUsernameWatchlistRoute
  '/user/$username/': typeof UserUsernameIndexRoute
  '/tv/$tvId_/season_/$seasonNumber': typeof TvTvIdSeasonSeasonNumberRoute
  '/tv/$tvId_/season_/$seasonNumber_/credits': typeof TvTvIdSeasonSeasonNumberCreditsRoute
  '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber': typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
  '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber_/credits': typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/goodbye'
    | '/reset-password'
    | '/search'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/verify-email'
    | '/welcome'
    | '/collections/$collectionId'
    | '/movies/$movieId'
    | '/person/$personId'
    | '/tv/$tvId'
    | '/movies'
    | '/tv'
    | '/movies/$movieId/credits'
    | '/tv/$tvId/credits'
    | '/tv/$tvId/episodes'
    | '/tv/$tvId/seasons'
    | '/user/$username/history'
    | '/user/$username/in-progress'
    | '/user/$username/lists'
    | '/user/$username/watchlist'
    | '/user/$username'
    | '/tv/$tvId/season/$seasonNumber'
    | '/tv/$tvId/season/$seasonNumber/credits'
    | '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
    | '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/goodbye'
    | '/reset-password'
    | '/search'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/verify-email'
    | '/welcome'
    | '/collections/$collectionId'
    | '/movies/$movieId'
    | '/person/$personId'
    | '/tv/$tvId'
    | '/movies'
    | '/tv'
    | '/movies/$movieId/credits'
    | '/tv/$tvId/credits'
    | '/tv/$tvId/episodes'
    | '/tv/$tvId/seasons'
    | '/user/$username/history'
    | '/user/$username/in-progress'
    | '/user/$username/lists'
    | '/user/$username/watchlist'
    | '/user/$username'
    | '/tv/$tvId/season/$seasonNumber'
    | '/tv/$tvId/season/$seasonNumber/credits'
    | '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
    | '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/goodbye'
    | '/reset-password'
    | '/search'
    | '/signin'
    | '/signup'
    | '/_auth/dashboard'
    | '/_auth/settings'
    | '/_auth/verify-email'
    | '/_auth/welcome'
    | '/collections/$collectionId'
    | '/movies/$movieId'
    | '/person/$personId'
    | '/tv/$tvId'
    | '/movies/'
    | '/tv/'
    | '/movies/$movieId_/credits'
    | '/tv/$tvId_/credits'
    | '/tv/$tvId_/episodes'
    | '/tv/$tvId_/seasons'
    | '/user/$username/history'
    | '/user/$username/in-progress'
    | '/user/$username/lists'
    | '/user/$username/watchlist'
    | '/user/$username/'
    | '/tv/$tvId_/season_/$seasonNumber'
    | '/tv/$tvId_/season_/$seasonNumber_/credits'
    | '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber'
    | '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber_/credits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoodbyeRoute: typeof GoodbyeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  PersonPersonIdRoute: typeof PersonPersonIdRoute
  TvTvIdRoute: typeof TvTvIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  TvIndexRoute: typeof TvIndexRoute
  MoviesMovieIdCreditsRoute: typeof MoviesMovieIdCreditsRoute
  TvTvIdCreditsRoute: typeof TvTvIdCreditsRoute
  TvTvIdEpisodesRoute: typeof TvTvIdEpisodesRoute
  TvTvIdSeasonsRoute: typeof TvTvIdSeasonsRoute
  UserUsernameHistoryRoute: typeof UserUsernameHistoryRoute
  UserUsernameInProgressRoute: typeof UserUsernameInProgressRoute
  UserUsernameListsRoute: typeof UserUsernameListsRoute
  UserUsernameWatchlistRoute: typeof UserUsernameWatchlistRoute
  UserUsernameIndexRoute: typeof UserUsernameIndexRoute
  TvTvIdSeasonSeasonNumberRoute: typeof TvTvIdSeasonSeasonNumberRoute
  TvTvIdSeasonSeasonNumberCreditsRoute: typeof TvTvIdSeasonSeasonNumberCreditsRoute
  TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute: typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute
  TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute: typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId': {
      id: '/tv/$tvId'
      path: '/tv/$tvId'
      fullPath: '/tv/$tvId'
      preLoaderRoute: typeof TvTvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$personId': {
      id: '/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof PersonPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/welcome': {
      id: '/_auth/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/user/$username/': {
      id: '/user/$username/'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/watchlist': {
      id: '/user/$username/watchlist'
      path: '/user/$username/watchlist'
      fullPath: '/user/$username/watchlist'
      preLoaderRoute: typeof UserUsernameWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/lists': {
      id: '/user/$username/lists'
      path: '/user/$username/lists'
      fullPath: '/user/$username/lists'
      preLoaderRoute: typeof UserUsernameListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/in-progress': {
      id: '/user/$username/in-progress'
      path: '/user/$username/in-progress'
      fullPath: '/user/$username/in-progress'
      preLoaderRoute: typeof UserUsernameInProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username/history': {
      id: '/user/$username/history'
      path: '/user/$username/history'
      fullPath: '/user/$username/history'
      preLoaderRoute: typeof UserUsernameHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/seasons': {
      id: '/tv/$tvId_/seasons'
      path: '/tv/$tvId/seasons'
      fullPath: '/tv/$tvId/seasons'
      preLoaderRoute: typeof TvTvIdSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/episodes': {
      id: '/tv/$tvId_/episodes'
      path: '/tv/$tvId/episodes'
      fullPath: '/tv/$tvId/episodes'
      preLoaderRoute: typeof TvTvIdEpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/credits': {
      id: '/tv/$tvId_/credits'
      path: '/tv/$tvId/credits'
      fullPath: '/tv/$tvId/credits'
      preLoaderRoute: typeof TvTvIdCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId_/credits': {
      id: '/movies/$movieId_/credits'
      path: '/movies/$movieId/credits'
      fullPath: '/movies/$movieId/credits'
      preLoaderRoute: typeof MoviesMovieIdCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/season_/$seasonNumber': {
      id: '/tv/$tvId_/season_/$seasonNumber'
      path: '/tv/$tvId/season/$seasonNumber'
      fullPath: '/tv/$tvId/season/$seasonNumber'
      preLoaderRoute: typeof TvTvIdSeasonSeasonNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/season_/$seasonNumber_/credits': {
      id: '/tv/$tvId_/season_/$seasonNumber_/credits'
      path: '/tv/$tvId/season/$seasonNumber/credits'
      fullPath: '/tv/$tvId/season/$seasonNumber/credits'
      preLoaderRoute: typeof TvTvIdSeasonSeasonNumberCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber': {
      id: '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber'
      path: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
      fullPath: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber'
      preLoaderRoute: typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber_/credits': {
      id: '/tv/$tvId_/season_/$seasonNumber_/episode_/$episodeNumber_/credits'
      path: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits'
      fullPath: '/tv/$tvId/season/$seasonNumber/episode/$episodeNumber/credits'
      preLoaderRoute: typeof TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoodbyeRoute: GoodbyeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  PersonPersonIdRoute: PersonPersonIdRoute,
  TvTvIdRoute: TvTvIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  TvIndexRoute: TvIndexRoute,
  MoviesMovieIdCreditsRoute: MoviesMovieIdCreditsRoute,
  TvTvIdCreditsRoute: TvTvIdCreditsRoute,
  TvTvIdEpisodesRoute: TvTvIdEpisodesRoute,
  TvTvIdSeasonsRoute: TvTvIdSeasonsRoute,
  UserUsernameHistoryRoute: UserUsernameHistoryRoute,
  UserUsernameInProgressRoute: UserUsernameInProgressRoute,
  UserUsernameListsRoute: UserUsernameListsRoute,
  UserUsernameWatchlistRoute: UserUsernameWatchlistRoute,
  UserUsernameIndexRoute: UserUsernameIndexRoute,
  TvTvIdSeasonSeasonNumberRoute: TvTvIdSeasonSeasonNumberRoute,
  TvTvIdSeasonSeasonNumberCreditsRoute: TvTvIdSeasonSeasonNumberCreditsRoute,
  TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute:
    TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberRoute,
  TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute:
    TvTvIdSeasonSeasonNumberEpisodeEpisodeNumberCreditsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
